export const address = [
  {
    city: "Addis Ababa",
    lat: "9.0300",
    lng: "38.7400",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Ādīs Ābeba",
    capital: "primary",
  },
  {
    city: "Ērer Sātā",
    lat: "9.5667",
    lng: "41.3833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Sumalē",
    capital: "",
  },
  {
    city: "Shashemenē",
    lat: "7.2000",
    lng: "38.6000",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "K’ebrī Dehar",
    lat: "6.7333",
    lng: "44.2667",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Sumalē",
    capital: "",
  },
  {
    city: "Nazrēt",
    lat: "8.5414",
    lng: "39.2689",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Mekele",
    lat: "13.4969",
    lng: "39.4769",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Tigray",
    capital: "admin",
  },
  {
    city: "Godē",
    lat: "5.9527",
    lng: "43.5516",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Sumalē",
    capital: "",
  },
  {
    city: "Āwasa",
    lat: "7.0500",
    lng: "38.4667",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "admin",
  },
  {
    city: "Dire Dawa",
    lat: "9.6000",
    lng: "41.8667",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Dirē Dawa",
    capital: "admin",
  },
  {
    city: "Bahir Dar",
    lat: "11.6000",
    lng: "37.3833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "admin",
  },
  {
    city: "Sodo",
    lat: "6.8550",
    lng: "37.7808",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Ārba Minch’",
    lat: "6.0333",
    lng: "37.5500",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Desē",
    lat: "11.1333",
    lng: "39.6333",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "",
  },
  {
    city: "Hosa’ina",
    lat: "7.5500",
    lng: "37.8500",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "K’ebrī Beyah",
    lat: "9.0833",
    lng: "43.0833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Sumalē",
    capital: "",
  },
  {
    city: "Jijiga",
    lat: "9.3500",
    lng: "42.8000",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Sumalē",
    capital: "admin",
  },
  {
    city: "Dīla",
    lat: "6.4083",
    lng: "38.3083",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Nek’emtē",
    lat: "9.0833",
    lng: "36.5500",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Debre Birhan",
    lat: "9.6833",
    lng: "39.5333",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "",
  },
  {
    city: "Debre Mark’os",
    lat: "10.3333",
    lng: "37.7167",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "",
  },
  {
    city: "Ferfer",
    lat: "5.0833",
    lng: "45.0833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Sumalē",
    capital: "",
  },
  {
    city: "Āwarē",
    lat: "8.2667",
    lng: "44.1500",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Sumalē",
    capital: "",
  },
  {
    city: "Harar",
    lat: "9.3111",
    lng: "42.1278",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Hārerī Hizb",
    capital: "admin",
  },
  {
    city: "Kombolcha",
    lat: "11.0867",
    lng: "39.7367",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "",
  },
  {
    city: "Jīma",
    lat: "7.6667",
    lng: "36.8333",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Debre Tabor",
    lat: "11.8500",
    lng: "38.0167",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "",
  },
  {
    city: "Harshin",
    lat: "9.2167",
    lng: "43.5878",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Sumalē",
    capital: "",
  },
  {
    city: "Ādīgrat",
    lat: "14.2667",
    lng: "39.4500",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Tigray",
    capital: "",
  },
  {
    city: "Debre Zeyit",
    lat: "8.7500",
    lng: "38.9833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Gambēla",
    lat: "8.2500",
    lng: "34.5833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Gambēla Hizboch",
    capital: "admin",
  },
  {
    city: "Mīzan Teferī",
    lat: "7.0000",
    lng: "35.5833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Ādwa",
    lat: "14.1667",
    lng: "38.9000",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Tigray",
    capital: "",
  },
  {
    city: "Gonder",
    lat: "12.6075",
    lng: "37.4592",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "",
  },
  {
    city: "Bodītī",
    lat: "6.8667",
    lng: "37.8667",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Āsela",
    lat: "7.9500",
    lng: "39.1167",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Āksum",
    lat: "14.1208",
    lng: "38.7278",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Tigray",
    capital: "",
  },
  {
    city: "Bonga",
    lat: "7.2667",
    lng: "36.2333",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub M‘irab Ītyop’iya Hizboch",
    capital: "admin",
  },
  {
    city: "Finote Selam",
    lat: "10.7000",
    lng: "37.2667",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "",
  },
  {
    city: "Semera",
    lat: "11.7922",
    lng: "41.0086",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āfar",
    capital: "admin",
  },
  {
    city: "Goba",
    lat: "7.0000",
    lng: "39.9833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Hāgere Hiywet",
    lat: "8.9833",
    lng: "37.8500",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Robē",
    lat: "7.1167",
    lng: "40.0000",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Yirga ‘Alem",
    lat: "6.7500",
    lng: "38.4167",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Giyon",
    lat: "8.5333",
    lng: "37.9667",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Bedēsa",
    lat: "6.8830",
    lng: "37.9329",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Āzezo",
    lat: "12.5586",
    lng: "37.4308",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Āmara",
    capital: "",
  },
  {
    city: "Butajīra",
    lat: "8.1208",
    lng: "38.3792",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Ālamat’ā",
    lat: "12.4167",
    lng: "39.5500",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Tigray",
    capital: "",
  },
  {
    city: "Āreka",
    lat: "7.0710",
    lng: "37.7076",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Gīmbī",
    lat: "9.1667",
    lng: "35.8333",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Wik’ro",
    lat: "13.7833",
    lng: "39.6000",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Tigray",
    capital: "",
  },
  {
    city: "Welk’īt’ē",
    lat: "8.2833",
    lng: "37.7833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Metu",
    lat: "8.3000",
    lng: "35.5833",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Fichē",
    lat: "9.8000",
    lng: "38.7333",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "K’olīto",
    lat: "7.3122",
    lng: "38.0892",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "YeDebub Bihēroch Bihēreseboch na Hizboch",
    capital: "",
  },
  {
    city: "Genet",
    lat: "9.0500",
    lng: "38.5000",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Āgaro",
    lat: "7.8558",
    lng: "36.5858",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Gelemso",
    lat: "8.8167",
    lng: "40.5167",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Oromīya",
    capital: "",
  },
  {
    city: "Āsosa",
    lat: "10.0667",
    lng: "34.5167",
    country: "Ethiopia",
    iso2: "ET",
    admin_name: "Bīnshangul Gumuz",
    capital: "admin",
  },
];
